apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-mongors1
    spec:
      capacity:
        storage: 2Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: manual
      hostPath:
        path: /mnt/data/mongors1
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-mongors2
    spec:
      capacity:
        storage: 2Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: manual
      hostPath:
        path: /mnt/data/mongors2
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-mongors3
    spec:
      capacity:
        storage: 2Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: manual
      hostPath:
        path: /mnt/data/mongors3
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-mongors1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: manual
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-mongors2
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: manual
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-mongors3
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: manual
