apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: mongors1a
      labels:
        app: mongodb
        instance: mongors1a
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        command: ["mongod"] # This overrides the default entrypoint
        args:  # This overrides the default CMD
        - "--replSet"
        - "rs1"
        - "--port"
        - "27018"
        - "--bind_ip_all"
        ports:
        - containerPort: 27018
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc-mongors1a
  - apiVersion: v1
    kind: Pod
    metadata:
      name: mongors1b
      labels:
        app: mongodb
        instance: mongors1b
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        command: ["mongod"]
        args:
        - "--replSet"
        - "rs1"
        - "--port"
        - "27018"
        - "--bind_ip_all"
        ports:
        - containerPort: 27018
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc-mongors1b
  - apiVersion: v1
    kind: Pod
    metadata:
      name: mongors1c
      labels:
        app: mongodb
        instance: mongors1c
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        command: ["mongod"]
        args:
        - "--replSet"
        - "rs1"
        - "--port"
        - "27018"
        - "--bind_ip_all"
        ports:
        - containerPort: 27018
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc-mongors1c