# create a service so that the pods can access each other with a sticky service name (instead of dynamic IP address)
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo1a
    spec:
      ports:
      - port: 27018
        targetPort: 27018
      selector:
        app: mongodb
        instance: mongors1a
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo1b
    spec:
      ports:
      - port: 27018
        targetPort: 27018
      selector:
        app: mongodb
        instance: mongors1b
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo1c
    spec:
      ports:
      - port: 27018
        targetPort: 27018
      selector:
        app: mongodb
        instance: mongors1c
