apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  ports:
  - port: 27017
    nodePort: 30001
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-deployment
