apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
  - name: mongodata-db
    hostPath: 
      path: /data/mongodata/db 
      type: DirectoryOrCreate
  - name: mongodata-configdb
    hostPath:
      path: /data/mongodata/configdb
      type: DirectoryOrCreate
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - name: mongodata-db
      mountPath: /data/db
    - name: mongodata-configdb
      mountPath: /data/configdb
    ports:
    - containerPort: 27017
    imagePullPolicy: Always
