apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
  - name: pv-storage-0001
    persistentVolumeClaim:
      claimName: pv0001-claim
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - mountPath: /data
      name: pv-storage-0001
    ports:
    - containerPort: 27017
    imagePullPolicy: Always
  #  hostPath:
  #    #path: /Users/duyhsieh/k8s_volume/mongo
  #    path: /data/mongo
  #    type: Directory
