apiVersion: v1
kind: Pod
metadata:
  name: lobby
  labels:
    app: lobby
spec:
  containers:
  - name: lobby
    image: bison-base
    imagePullPolicy: Never  # Use Never if you want to ensure no pull attempts
    ports:
    - containerPort: 80

    command: ["sh"] # This overrides the default entrypoint
    args:  # This overrides the default CMD
        - "-c"
        - "tail -f /dev/null"
    env:  # Environment variables section should be inside the container spec
    - name: "ENV"
      valueFrom:  # Correct the field names to proper case sensitivity
        configMapKeyRef:
          name: "lobby-configmap"
          key: "ENV"
    - name: "GAMETYPE"
      valueFrom:
        configMapKeyRef:
          name: "lobby-configmap"
          key: "GAMETYPE"
    
    volumeMounts:
    - name: workdir
      mountPath: /mnt/data

  volumes:
  - name: workdir
    hostPath:
      path: "/data"
      type: Directory